spring:
  profiles:
    active: dev
jwt:
  # 签发人
  issuer: Jovan
  # 秘钥
  secret: ajOpgbcP6KcQvd5GOe1Hg/7py6pMxvg6pziibjf2WpTrQFPR6vgfIJaRHrLtVeXdT51n9LEhku/QZ13J7xoWkA==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer